
api:
    path: '%modera_direct.routes_prefix%/api.js'
    defaults:
        _controller: Modera\DirectBundle\Controller\DirectController::getApiAction
remoting:
    path: '%modera_direct.routes_prefix%/remoting.js'
    defaults:
        _controller: Modera\DirectBundle\Controller\DirectController::getRemotingAction
route:
    path: '%modera_direct.routes_prefix%/route'
    defaults:
        _controller: Modera\DirectBundle\Controller\DirectController::routeAction
